/**
 * ChatToolbar.java
 *
 * @author Aaron Toth
 *
 * Copyright (C) 2009 Justin Cole, Aaron Jankun, David Marczak, Vineet Sharma,
 *        and Aaron Toth
 *
 * This file is part of Wernicke.
 *
 * Wernicke is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package grimace.client;

public class ChatToolbar extends javax.swing.JPanel {

    /** Creates new form ChatToolbar */
    public ChatToolbar() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        bolden = new javax.swing.JToggleButton();
        italicise = new javax.swing.JToggleButton();
        underline = new javax.swing.JToggleButton();
        jComboBox1 = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton1 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(0, 36));
        setPreferredSize(new java.awt.Dimension(300, 36));

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setMargin(new java.awt.Insets(2, 0, 2, 0));
        jToolBar1.setMinimumSize(new java.awt.Dimension(156, 36));
        jToolBar1.setPreferredSize(new java.awt.Dimension(184, 36));

        bolden.setFont(new java.awt.Font("Lucida Grande", 0, 14));
        bolden.setText("<html><strong>B</strong>");
        bolden.setFocusable(false);
        bolden.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bolden.setMaximumSize(new java.awt.Dimension(25, 28));
        bolden.setMinimumSize(new java.awt.Dimension(25, 28));
        bolden.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(bolden);

        italicise.setFont(new java.awt.Font("Lucida Grande", 0, 14));
        italicise.setText("<html><i>i</i>");
        italicise.setFocusable(false);
        italicise.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        italicise.setMaximumSize(new java.awt.Dimension(25, 28));
        italicise.setMinimumSize(new java.awt.Dimension(25, 28));
        italicise.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(italicise);

        underline.setFont(new java.awt.Font("Lucida Grande", 0, 14));
        underline.setText("<html><u>U</u>");
        underline.setFocusable(false);
        underline.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        underline.setMaximumSize(new java.awt.Dimension(25, 28));
        underline.setMinimumSize(new java.awt.Dimension(25, 28));
        underline.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(underline);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Arial", "Times", "Helvetica", "Courier", "Calibri" }));
        jComboBox1.setMaximumSize(new java.awt.Dimension(125, 27));
        jComboBox1.setMinimumSize(new java.awt.Dimension(125, 27));
        jComboBox1.setPreferredSize(new java.awt.Dimension(20, 27));
        jToolBar1.add(jComboBox1);
        jToolBar1.add(jSeparator1);

        jButton1.setText("Add Equation");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bolden;
    private javax.swing.JToggleButton italicise;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToggleButton underline;
    // End of variables declaration//GEN-END:variables

}
